### ISSUE TITLE
Announce the IBA 2018 Gold Stevie wins

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#9]
Metanorma has won the following entries at the 15th International Business Awards:

* Gold Stevie Award: Best New Product or Service of the Year - Content - Semantic Technology Platform, Tools and Applications
* Gold Stevie Award: Best New Product or Service of the Year - Content - Scholarly Publishing Information Solution

We should put this on the site. The logo is uploaded in 9bbdb87486ce3db5f37e6a0c91db35644c93bd95.

**Comment by strogonoff** [comment]
@ronaldtse Great opportunity for a blog post. After a cursory search I’m not seeing any fellow winners overly promoting the award on their product sites, so as far as my judgement I’d just have the post and the logo can be featured there.

Open to suggestions though, it’d be straightforward to fit the logo on the landing page while the award is fresh.

**Comment by strogonoff** [comment]
For the blog to look as designed [posts need author info in frontmatter](https://github.com/riboseinc/jekyll-theme-open-project#posts) in following format

```yaml
---
author:
  email: <author’s email>
  name: <author’s full name>
  social_links:
    - https://twitter.com/username
    - https://facebook.com/username
    - https://linkedin.com/in/username
---
```

As designed, theme anticipates one author per blog post to be specified. For author pic to be displayed, theme would use Gravatar associated with author’s email.
